\copy raw.schools (school_id, school_name, school_code) FROM '/seed_data/schools.csv' WITH (FORMAT csv, HEADER true);
\copy raw.terms (term_id, term_name, academic_year, term_start_date, census_date, term_end_date) FROM '/seed_data/terms.csv' WITH (FORMAT csv, HEADER true);
\copy raw.programs (program_id, school_id, program_name, degree_level, cip_code) FROM '/seed_data/programs.csv' WITH (FORMAT csv, HEADER true);
\copy raw.students (student_id, student_type, residency_status, entry_term_id, admit_school_id, admit_program_id, synthetic_birth_year) FROM '/seed_data/students.csv' WITH (FORMAT csv, HEADER true);
\copy raw.course_sections (section_id, term_id, school_id, program_id, course_code, section_number, modality, capacity) FROM '/seed_data/course_sections.csv' WITH (FORMAT csv, HEADER true);
\copy raw.applications (application_id, student_id, term_id, school_id, program_id, application_date, application_status) FROM '/seed_data/applications.csv' WITH (FORMAT csv, HEADER true);
\copy raw.admissions (admission_id, application_id, decision_date, decision_status) FROM '/seed_data/admissions.csv' WITH (FORMAT csv, HEADER true);
\copy raw.deposits (deposit_id, admission_id, deposit_date, deposit_status, deposit_amount) FROM '/seed_data/deposits.csv' WITH (FORMAT csv, HEADER true);
\copy raw.registrations (registration_id, student_id, section_id, term_id, registration_date, registration_status, credit_hours, grade_mode) FROM '/seed_data/registrations.csv' WITH (FORMAT csv, HEADER true);
\copy raw.enrollment_census (enrollment_id, student_id, term_id, school_id, program_id, census_enrolled_flag, ipeds_enrolled_flag, total_credit_hours, enrollment_status) FROM '/seed_data/enrollment_census.csv' WITH (FORMAT csv, HEADER true);
\copy raw.budget_actuals (budget_actual_id, fiscal_year, school_id, revenue_budget, revenue_actual, expense_budget, expense_actual) FROM '/seed_data/budget_actuals.csv' WITH (FORMAT csv, HEADER true);
