model Model
	culture: en-US
	annotation PBI_ProTooling = "Sample"

expression ProjectRoot = "C:\Users\YourName\nsu-modernization-demo" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
	annotation PBI_ResultType = Text
expression LakehouseName = "NSU_DEMO" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
	annotation PBI_ResultType = Text

	table FactEnrollment
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceTable = "FactEnrollment"
	column registration_id
	dataType: string
		sourceColumn: registration_id
	column student_id
	dataType: string
		sourceColumn: student_id
	column section_id
	dataType: string
		sourceColumn: section_id
	column term_id
	dataType: string
		sourceColumn: term_id
	column school_id
	dataType: string
		sourceColumn: school_id
	column program_id
	dataType: string
		sourceColumn: program_id
	column registration_status
	dataType: string
		sourceColumn: registration_status
	column credit_hours
	dataType: double
		sourceColumn: credit_hours
	measure Enrolled = CALCULATE(DISTINCTCOUNT(FactEnrollment[registration_id]), FactEnrollment[registration_status] = "Registered")
	formatString: "#,0"

	partition FactEnrollment = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\mart_tables\fact_enrollment.csv"), [Delimiter=",", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"registration_id", type text}, {"student_id", type text}, {"section_id", type text}, {"term_id", type text}, {"school_id", type text}, {"program_id", type text}, {"registration_status", type text}, {"credit_hours", type number}})
				in
					#"Changed Type"

	table RecruitmentFunnel
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceTable = "RecruitmentFunnel"
	column application_id
	dataType: string
		sourceColumn: application_id
	column term_id
	dataType: string
		sourceColumn: term_id
	column school_id
	dataType: string
		sourceColumn: school_id
	column program_id
	dataType: string
		sourceColumn: program_id
	column application_status
	dataType: string
		sourceColumn: application_status
	column decision_status
	dataType: string
		sourceColumn: decision_status
	column deposit_status
	dataType: string
		sourceColumn: deposit_status
	measure Applications = CALCULATE(DISTINCTCOUNT(RecruitmentFunnel[application_id]), RecruitmentFunnel[application_status] = "Submitted")
	formatString: "#,0"
	measure Admits = CALCULATE(DISTINCTCOUNT(RecruitmentFunnel[application_id]), RecruitmentFunnel[decision_status] = "Admitted")
	formatString: "#,0"
	measure Deposits = CALCULATE(DISTINCTCOUNT(RecruitmentFunnel[application_id]), RecruitmentFunnel[deposit_status] = "Paid")
	formatString: "#,0"
	measure Yield = DIVIDE([Deposits], [Admits])
	formatString: "0.0%"

	partition RecruitmentFunnel = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\mart_tables\fact_recruitment_funnel.csv"), [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"application_id", type text}, {"student_id", type text}, {"term_id", type text}, {"school_id", type text}, {"program_id", type text}, {"application_status", type text}, {"admission_id", type text}, {"decision_status", type text}, {"deposit_id", type text}, {"deposit_status", type text}, {"deposit_amount", type number}, {"is_admitted", type logical}, {"is_deposited", type logical}})
				in
					#"Changed Type"

	table CensusEnrollment
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceTable = "CensusEnrollment"
	column enrollment_id
	dataType: string
		sourceColumn: enrollment_id
	column student_id
	dataType: string
		sourceColumn: student_id
	column term_id
	dataType: string
		sourceColumn: term_id
	column school_id
	dataType: string
		sourceColumn: school_id
	column program_id
	dataType: string
		sourceColumn: program_id
	column census_enrolled_flag
	dataType: boolean
		sourceColumn: census_enrolled_flag
	column ipeds_enrolled_flag
	dataType: boolean
		sourceColumn: ipeds_enrolled_flag
	measure CensusEnrollment = CALCULATE(DISTINCTCOUNT(CensusEnrollment[student_id]), CensusEnrollment[census_enrolled_flag] = TRUE())
	formatString: "#,0"
	measure IpedsEnrollment = CALCULATE(DISTINCTCOUNT(CensusEnrollment[student_id]), CensusEnrollment[ipeds_enrolled_flag] = TRUE())
	formatString: "#,0"
	defaultPowerBIDataSourceVersion: powerBI_V3
	sourceQueryCulture: en-US
	valueFilterBehavior: independent
	dataAccessOptions
		legacyRedirects
		returnErrorValuesAsNull

	partition CensusEnrollment = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\mart_tables\fact_census_enrollment.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"enrollment_id", type text}, {"student_id", type text}, {"term_id", type text}, {"school_id", type text}, {"program_id", type text}, {"census_enrolled_flag", type logical}, {"ipeds_enrolled_flag", type logical}, {"total_credit_hours", type number}, {"enrollment_status", type text}})
				in
					#"Changed Type"

table dim_school
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceSnapshot = "seeds/dimension_tables/dim_school.csv"
	column school_id
	dataType: string
	isKey
		sourceColumn: school_id
	column school_name
	dataType: string
		sourceColumn: school_name
	column school_code
	dataType: string
		sourceColumn: school_code
	partition dim_school = m
	mode: import
		source =
	let
	Source = Csv.Document(File.Contents(ProjectRoot & "\\seeds\\dimension_tables\\dim_school.csv"), [Delimiter=", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
	#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
	#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"school_id", type text}, {"school_name", type text}, {"school_code", type text}})
	in
	#"Changed Type"

	table dim_program
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceSnapshot = "seeds/dimension_tables/dim_program.csv"
	column program_id
	dataType: string
	isKey
		sourceColumn: program_id
	column school_id
	dataType: string
		sourceColumn: school_id
	column program_name
	dataType: string
		sourceColumn: program_name
	column degree_level
	dataType: string
		sourceColumn: degree_level
	column cip_code
	dataType: string
		sourceColumn: cip_code
	partition dim_program = m
	mode: import
		source =
	let
	Source = Csv.Document(File.Contents(ProjectRoot & "\\seeds\\dimension_tables\\dim_program.csv"), [Delimiter=", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
	#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
	#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"program_id", type text}, {"school_id", type text}, {"program_name", type text}, {"degree_level", type text}, {"cip_code", type text}})
	in
	#"Changed Type"

	table dim_term
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceSnapshot = "seeds/dimension_tables/dim_term.csv"
	column term_id
	dataType: string
	isKey
		sourceColumn: term_id
	column term_name
	dataType: string
		sourceColumn: term_name
	column academic_year
	dataType: string
		sourceColumn: academic_year
	column term_start_date
	dataType: dateTime
		sourceColumn: term_start_date
	column census_date
	dataType: dateTime
		sourceColumn: census_date
	column term_end_date
	dataType: dateTime
		sourceColumn: term_end_date
	partition dim_term = m
	mode: import
		source =
	let
	Source = Csv.Document(File.Contents(ProjectRoot & "\\seeds\\dimension_tables\\dim_term.csv"), [Delimiter=", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
	#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
	#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"term_id", type text}, {"term_name", type text}, {"academic_year", type text}, {"term_start_date", type date}, {"census_date", type date}, {"term_end_date", type date}})
	in
	#"Changed Type"

relationship FactEnrollment_school {
	fromColumn: FactEnrollment.school_id
	toColumn: dim_school.school_id
	crossFilteringBehavior: singleDirection
}
relationship FactEnrollment_program {
	fromColumn: FactEnrollment.program_id
	toColumn: dim_program.program_id
	crossFilteringBehavior: singleDirection
}
relationship FactEnrollment_term {
	fromColumn: FactEnrollment.term_id
	toColumn: dim_term.term_id
	crossFilteringBehavior: singleDirection
}
relationship RecruitmentFunnel_school {
	fromColumn: RecruitmentFunnel.school_id
	toColumn: dim_school.school_id
	crossFilteringBehavior: singleDirection
}
relationship RecruitmentFunnel_program {
	fromColumn: RecruitmentFunnel.program_id
	toColumn: dim_program.program_id
	crossFilteringBehavior: singleDirection
}
relationship RecruitmentFunnel_term {
	fromColumn: RecruitmentFunnel.term_id
	toColumn: dim_term.term_id
	crossFilteringBehavior: singleDirection
}
relationship CensusEnrollment_school {
	fromColumn: CensusEnrollment.school_id
	toColumn: dim_school.school_id
	crossFilteringBehavior: singleDirection
}
relationship CensusEnrollment_program {
	fromColumn: CensusEnrollment.program_id
	toColumn: dim_program.program_id
	crossFilteringBehavior: singleDirection
}
relationship CensusEnrollment_term {
	fromColumn: CensusEnrollment.term_id
	toColumn: dim_term.term_id
	crossFilteringBehavior: singleDirection
}
annotation __PBI_TimeIntelligenceEnabled = 1
annotation PBI_ProTooling = ["DevMode"]

ref cultureInfo en-US
