table dim_program
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceSnapshot = "seeds/dimension_tables/dim_program.csv"
	column program_id
		dataType: string
		isKey
		sourceColumn: program_id
	column school_id
		dataType: string
		sourceColumn: school_id
	column program_name
		dataType: string
		sourceColumn: program_name
	column degree_level
		dataType: string
		sourceColumn: degree_level
	column cip_code
		dataType: string
		sourceColumn: cip_code

	partition dim_program = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\dimension_tables\dim_program.csv"), [Delimiter=",", Columns=5, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"program_id", type text}, {"school_id", type text}, {"program_name", type text}, {"degree_level", type text}, {"cip_code", type text}})
				in
					#"Changed Type"
