table dim_school
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceSnapshot = "seeds/dimension_tables/dim_school.csv"
	column school_id
		dataType: string
		isKey
		sourceColumn: school_id
	column school_name
		dataType: string
		sourceColumn: school_name
	column school_code
		dataType: string
		sourceColumn: school_code

	partition dim_school = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\dimension_tables\dim_school.csv"), [Delimiter=",", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"school_id", type text}, {"school_name", type text}, {"school_code", type text}})
				in
					#"Changed Type"
