table FactEnrollment
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceTable = "FactEnrollment"
	column registration_id
		dataType: string
		sourceColumn: registration_id
	column student_id
		dataType: string
		sourceColumn: student_id
	column section_id
		dataType: string
		sourceColumn: section_id
	column term_id
		dataType: string
		sourceColumn: term_id
	column school_id
		dataType: string
		sourceColumn: school_id
	column program_id
		dataType: string
		sourceColumn: program_id
	column registration_status
		dataType: string
		sourceColumn: registration_status
	column credit_hours
		dataType: double
		sourceColumn: credit_hours
	measure Enrolled = CALCULATE(DISTINCTCOUNT(FactEnrollment[registration_id]), FactEnrollment[registration_status] = "Registered")
		formatString: "#,0"

	partition FactEnrollment = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\mart_tables\fact_enrollment.csv"), [Delimiter=",", Columns=18, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"registration_id", type text}, {"student_id", type text}, {"section_id", type text}, {"term_id", type text}, {"school_id", type text}, {"program_id", type text}, {"registration_status", type text}, {"credit_hours", type number}})
				in
					#"Changed Type"
