	table RecruitmentFunnel
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceTable = "RecruitmentFunnel"
	column application_id
	dataType: string
		sourceColumn: application_id
	column term_id
	dataType: string
		sourceColumn: term_id
	column school_id
	dataType: string
		sourceColumn: school_id
	column program_id
	dataType: string
		sourceColumn: program_id
	column application_status
	dataType: string
		sourceColumn: application_status
	column decision_status
	dataType: string
		sourceColumn: decision_status
	column deposit_status
	dataType: string
		sourceColumn: deposit_status
	measure Applications = CALCULATE(DISTINCTCOUNT(RecruitmentFunnel[application_id]), RecruitmentFunnel[application_status] = "Submitted")
	formatString: "#,0"
	measure Admits = CALCULATE(DISTINCTCOUNT(RecruitmentFunnel[application_id]), RecruitmentFunnel[decision_status] = "Admitted")
	formatString: "#,0"
	measure Deposits = CALCULATE(DISTINCTCOUNT(RecruitmentFunnel[application_id]), RecruitmentFunnel[deposit_status] = "Paid")
	formatString: "#,0"
	measure Yield = DIVIDE([Deposits], [Admits])
	formatString: "0.0%"

	partition RecruitmentFunnel = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\mart_tables\fact_recruitment_funnel.csv"), [Delimiter=",", Columns=16, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"application_id", type text}, {"student_id", type text}, {"term_id", type text}, {"school_id", type text}, {"program_id", type text}, {"application_status", type text}, {"admission_id", type text}, {"decision_status", type text}, {"deposit_id", type text}, {"deposit_status", type text}, {"deposit_amount", type number}, {"is_admitted", type logical}, {"is_deposited", type logical}})
				in
					#"Changed Type"
