table CensusEnrollment
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceTable = "CensusEnrollment"
	column enrollment_id
		dataType: string
		sourceColumn: enrollment_id
	column student_id
		dataType: string
		sourceColumn: student_id
	column term_id
		dataType: string
		sourceColumn: term_id
	column school_id
		dataType: string
		sourceColumn: school_id
	column program_id
		dataType: string
		sourceColumn: program_id
	column census_enrolled_flag
		dataType: boolean
		sourceColumn: census_enrolled_flag
	column ipeds_enrolled_flag
		dataType: boolean
		sourceColumn: ipeds_enrolled_flag
	measure CensusEnrollment = CALCULATE(DISTINCTCOUNT(CensusEnrollment[student_id]), CensusEnrollment[census_enrolled_flag] = TRUE())
		formatString: "#,0"
	measure IpedsEnrollment = CALCULATE(DISTINCTCOUNT(CensusEnrollment[student_id]), CensusEnrollment[ipeds_enrolled_flag] = TRUE())
		formatString: "#,0"
	defaultPowerBIDataSourceVersion: powerBI_V3
	sourceQueryCulture: en-US
	valueFilterBehavior: independent
	dataAccessOptions
		legacyRedirects
		returnErrorValuesAsNull

	partition CensusEnrollment = m
		mode: import
		source =
				let
					Source = Csv.Document(File.Contents(ProjectRoot & "\seeds\mart_tables\fact_census_enrollment.csv"), [Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
					#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"enrollment_id", type text}, {"student_id", type text}, {"term_id", type text}, {"school_id", type text}, {"program_id", type text}, {"census_enrolled_flag", type logical}, {"ipeds_enrolled_flag", type logical}, {"total_credit_hours", type number}, {"enrollment_status", type text}})
				in
					#"Changed Type"
