table quality_test_evidence
	annotation SourceSystem = "OneLake Lakehouse NSU_DEMO"
	annotation SourceSnapshot = "seeds/mart_tables/quality_test_evidence.csv"
	column test_name
	dataType: string
		sourceColumn: test_name
	column result
	dataType: string
		sourceColumn: result
	column evidence
	dataType: string
		sourceColumn: evidence
	partition quality_test_evidence = m
	mode: import
		source =
	let
	Source = Csv.Document(File.Contents(ProjectRoot & "\\seeds\\mart_tables\\quality_test_evidence.csv"), [Delimiter=", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
	#"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
	#"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"test_name", type text}, {"result", type text}, {"evidence", type text}})
	in
	#"Changed Type"
